name: coffee_shop_app
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/extra_ingredients/
    - assets/images/coffee/
    - assets/images/coffee_shops/
    - assets/images/people/
    - assets/images/ingredients/
  fonts:
    - family: varela
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
    - family: nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300