name: tesla_app
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  action_slider: ^0.7.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  modal_bottom_sheet: ^3.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
