name: furnitureui
description: "A new Flutter project."

version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Monologue
      fonts:
        - asset: assets/fonts/Monologue_DEMO.ttf
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.otf
        - asset: assets/fonts/SFPRODISPLAYBOLD.otf
          weight: 700
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.otf
          weight: 500