name: mobank
description: "Mobile Bank UI."
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  mobile_scanner: ^5.2.1
  modal_bottom_sheet: ^3.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
