name: ford_app
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
      # ford 1
      - assets/cars/ford1/car1.png
      - assets/cars/ford1/car2.png
      - assets/cars/ford1/car3.png
      - assets/cars/ford1/car4.png
      # ford 2
      - assets/cars/ford2/car1.png
      - assets/cars/ford2/car2.png
      - assets/cars/ford2/car3.png
      - assets/cars/ford2/car4.png
      - assets/cars/ford2/car5.png
      # home_page_car
      - assets/cars/home_page_1.png
      # profile_image
      - assets/profile.png

  fonts:
    - family: Elmessiri
      fonts:
        - asset: assets/fonts/elmessiri-bold.otf
          weight: 700
        - asset: assets/fonts/elmessiri-medium.otf
          weight: 500
        - asset: assets/fonts/elmessiri-regular.otf
          weight: 400
        - asset: assets/fonts/elmessiri-semibold.otf
          weight: 600
    - family: SecondaSoft
      fonts:
        - asset: assets/fonts/secondasoft/SecondaSoftBold.otf
          weight: 300
        - asset: assets/fonts/secondasoft/SecondaSoftMedium.otf
          weight: 500
        - asset: assets/fonts/secondasoft/SecondaSoftRegular.otf
          weight: 400
        - asset: assets/fonts/secondasoft/SecondaSoftBlack.otf
          weight: 600