name: nikeyshoper
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
    smooth_page_indicator: ^1.2.0+3
    dio: ^5.7.0
    intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
