name: coffee_house_app
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/coffees/
    - assets/coffees/1/
    - assets/coffees/2/
    - assets/coffees/3/
    - assets/coffees/4/
    - assets/coffees/5/