name: shoe_store_app
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/onboarding/
  fonts:
    - family: Montserrat-light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
    - family: Montserrat-regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat-medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat-black
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf