name: bloom
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: worksans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
          weight: 700