name: carrentui
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  animate_do: ^3.3.4
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  show_up_animation: ^2.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
