name: fast_food_app
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
assets:
  - assets/icons/
  - assets/other_icons/
  - assets/images/
  - assets/images/donuts/
  - assets/images/smoothies/
  - assets/images/pizzas/
  - assets/images/pizzas/remix/