name: pizzaapp
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/onboarding/
    - assets/ingredients/
    - assets/ingredients/single_units/
    - assets/pizzabox/
    - assets/pizzas/